language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t kartikey/docker-react -f Dockerfile.dev .





script: 
  - docker run -e CI=true kartikey/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-509017441367"
  bucket-path: "docker-react"
  on:
    branch: master
    
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY