language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t kartikey/docker-react -f Dockefile.dev .





script: 
  - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage